name:                echobot
version:             0.1.0.0
github:              "urbanizzz/echobot"
license:             BSD3
author:              "urbanizzz"
maintainer:          "yuraoskin@gmail.com"
copyright:           "urbanizzz"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/urbanizzz/echobot#readme>

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bytestring
  - containers
  - extra
  - fast-logger
  - mtl
  - scientific
  - text
  - yaml

default-extensions:
  - OverloadedStrings
  - RecordWildCards

library:
  source-dirs: src

executables:
  echobot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - echobot
    when:
    - condition: false
      other-modules: Paths_echobot

tests:
  echobot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - echobot
    - QuickCheck
